#!/bin/bash
set -euf -o pipefail
mkdir -p /home/nao/ros1_dependencies_sources/build/bullet
cd /home/nao/ros1_dependencies_sources/build/bullet
cmake  \
  -DCMAKE_INSTALL_PREFIX=/home/nao/${INSTALL_ROOT}/ros1_dependencies \
  -DCMAKE_BUILD_TYPE=Release \
  -BUILD_CPU_DEMOS=OFF \
  -DBUILD_SHARED_LIBS=ON \
  ../../src/bullet3
make -j4 install
