#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/nao/ros1_dependencies_sources/src/collada-dom/debian/debian
SOURCE_DIR=/home/nao/ros1_dependencies_sources/src/collada-dom/collada-dom-2.4.4

cd ${DEBIAN_DIR}/patches
if [ ! -e .patched ]; then
    for patch_file in $(cat series); do
        OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false)
    done
    touch .patched
fi

#
mkdir -p /home/nao/ros1_dependencies_sources/build/collada-dom
cd /home/nao/ros1_dependencies_sources/build/collada-dom
cmake \
  -DLIBXML2_FOUND=1 -DLIBXML2_INCLUDE_DIR=/home/nao/ctc/xml2/include/libxml2 -DLIBXML2_LIBRARY_DIR=/home/nao/ctc/xml2/lib -DLIBXML2_LIBRARIES="/home/nao/ctc/xml2/lib/libxml2.so" \
  -Dlibpcrecpp_FOUND=1 -DHAVE_PCRECPP_H=1 -Dlibpcrecpp_INCLUDE_DIRS=/home/nao/ctc/pcre/include -Dlibpcrecpp_LIBRARY_DIRS=/home/nao/ctc/pcre/lib -Dlibpcrecpp_LIBRARIES="/home/nao/ctc/pcre/lib/libpcre.so.1;/home/nao/ctc/pcre/lib/libpcrecpp.so" \
  -DCMAKE_FIND_ROOT_PATH="/home/nao/System/ros1_dependencies;/home/nao/ctc" \
  -DCMAKE_INSTALL_PREFIX=/home/nao/${INSTALL_ROOT}/ros1_dependencies \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_SKIP_RPATH=ON \
  -DENABLE_SSE=OFF -DENABLE_SSE2=OFF -DENABLE_SSSE3=OFF \
  -DOPT_COLLADA15=ON \
  -DOPT_COLLADA14=ON \
  -DOPT_COMPILE_VIEWER=OFF \
  -DOPT_COMPILE_FX=OFF \
  -DOPT_COMPILE_RT=OFF \
  -DOPT_BUILD_PACKAGES=OFF \
  -DOPT_BUILD_PACKAGE_DEFAULT=OFF \
  -DOPT_DOUBLE_PRECISION=ON \
  ${SOURCE_DIR}

make -j4 install VERBOSE=1
