#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/nao/ros1_dependencies_sources/src/yaml-cpp/debian/debian
SOURCE_DIR=/home/nao/ros1_dependencies_sources/src/yaml-cpp/yaml-cpp-release-0.5.2

cd ${DEBIAN_DIR}/patches
for patch_file in $(cat series); do
    OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false)
done

mkdir -p /home/nao/ros1_dependencies_sources/build/yaml-cpp
cd /home/nao/ros1_dependencies_sources/build/yaml-cpp

cmake \
  -DCMAKE_FIND_ROOT_PATH="/home/nao/ros1_dependencies;/home/nao/ctc" \
  -DCMAKE_INSTALL_PREFIX=/home/nao/${INSTALL_ROOT}/ros1_dependencies \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=ON \
  -DYAML_CPP_BUILD_TOOLS=ON \
  ${SOURCE_DIR}

make -j4 install

echo "
  -DCMAKE_TOOLCHAIN_FILE=/home/nao/ctc-cmake-toolchain.cmake \
  -DALDE_CTC_CROSS=/home/nao/ctc \
"
