#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/nao/ros1_dependencies_sources/src/db5/debian/debian
SOURCE_DIR=/home/nao/ros1_dependencies_sources/src/db5/db-5.3.28

#
# constantly does not have patches
#
cd ${DEBIAN_DIR}/patches
for patch_file in $(grep -v ^# series); do
    OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false) || echo "OK"
done

cd ${SOURCE_DIR}/build_unix

../dist/configure --prefix=/home/nao/${INSTALL_ROOT}/ros1_dependencies --build $(uname -m)-unknown-linux-gnu --enable-cxx --enable-compat185  --host=i686-aldebaran-linux-gnu

make -j1 install
