#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/nao/ros1_dependencies_sources/src/jack-audio-connection-kit/debian/debian
SOURCE_DIR=/home/nao/ros1_dependencies_sources/src/jack-audio-connection-kit/jackd1-0.125.0

#
# constantly does not have patches
#
cd ${DEBIAN_DIR}/patches
for patch_file in $(grep -v ^# series); do
    OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false) || echo "OK"
done

cd ${SOURCE_DIR}

./autogen.sh
./configure --enable-force-install --prefix=/home/nao/${INSTALL_ROOT}/ros1_dependencies --host=i686-aldebaran-linux-gnu

make -j4 install
