#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/nao/ros1_dependencies_sources/src/libncurses/debian/debian
SOURCE_DIR=/home/nao/ros1_dependencies_sources/src/libncurses/ncurses-6.1

#
cd ${DEBIAN_DIR}/patches
for patch_file in $(grep -v ^# series); do
    OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false) || echo "OK"
done

cd ${SOURCE_DIR}

./configure --prefix=/home/nao/${INSTALL_ROOT}/ros1_dependencies -with-shared  --host=i686-aldebaran-linux-gnu

make -j4 install
