#!/bin/bash
set -xeu -o pipefail

DEBIAN_DIR=/home/nao/ros1_dependencies_sources/src/speech_tools/debian/debian
SOURCE_DIR=/home/nao/ros1_dependencies_sources/src/speech_tools/speech_tools

#
cd ${DEBIAN_DIR}/patches
if [ ! -e .patched ]; then
    for patch_file in $(grep -v ^# series); do
        OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false) || echo "OK"
    done
fi
touch .patched

cd ${SOURCE_DIR}

aclocal
autoconf

export PROJECT_VERSION=2.5.0
export PROJECT_MAJOR_VERSION=2

./configure --prefix=/home/nao/${INSTALL_ROOT}/ros1_dependencies --host=i686-aldebaran-linux-gnu

sed -i 's@^ifndef LIBS$@ifndef LIBS_ignored@' ${SOURCE_DIR}/config/rules/defaults.mak
make clean
#	$(strip $(LINK_COMMAND) -o $@ $@_main.o $(LIBS) -L../lib -leststring -lestbase -lestools -lasound -lncurses $($(@:=_LIBS)))
#make -j1 PULSEAUDIO=none CC=/home/nao/ctc/bin/i686-aldebaran-linux-gnu-gcc CXX=/home/nao/ctc/bin/i686-aldebaran-linux-gnu-g++ AR=${AR:-ar} RANLIB=${RANLIB:-ranlib} SHARED_LINKFLAGS="-Wl,--no-as-needed" VERBOSE=1
#CXX=${CXX:-g++} CC=${CC:-gcc} AR=${AR:-ar} RANLIB=${RANLIB:-ranlib} VERBOSE=1
#unset LIBS
#touch main/.make_execs main/.sub_directories
LIBS="" make \
    -j1 PULSEAUDIO=none CXX=${CXX:-g++} CC=${CC:-gcc} AR=${AR:-ar} RANLIB=${RANLIB:-ranlib} VERBOSE=1 \
    OS_LIBS="-L/home/nao/${INSTALL_ROOT}/ros1_dependencies/lib -ldl -lncurses"
#     LDFLAGS="-L/home/nao/${INSTALL_ROOT}/ros1_dependencies/lib -L/home/nao/System/Python-2.7.17/lib -L/home/nao/ctc/bzip2/lib -L/home/nao/ctc/openssl/lib -L/home/nao/ctc/xz_utils/lib -L/home/nao/ctc/tiff/lib -L/home/nao/ctc/jpeg/lib -L/home/nao/ctc/png/lib -L/home/nao/ctc/xml2/lib -L/home/nao/ctc/pcre/lib -L/home/nao/ctc/ogg/lib"


cp lib/*.a    /home/nao/${INSTALL_ROOT}/ros1_dependencies/lib
cp lib/*.so.* /home/nao/${INSTALL_ROOT}/ros1_dependencies/lib
