#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/nao/ros1_dependencies_sources/src/gpgconf/debian/debian
SOURCE_DIR=/home/nao/ros1_dependencies_sources/src/gpgconf/gnupg-2.2.4

cd ${DEBIAN_DIR}/patches
if [ ! -e .patched ]; then
    for patch_file in $(cat series); do
        OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false)
    done
    touch .patched
fi

cd ${SOURCE_DIR}

make clean || echo "OK"
autoconf
./configure \
  --host=i686-aldebaran-linux-gnu \
  --prefix=/home/nao/${INSTALL_ROOT}/ros1_dependencies \
  --enable-wks-tools \
  --enable-all-tests \
  --with-agent-s2k-calibration=300 \
  --enable-symcryptrun --enable-large-secmem


#make -j4 install
(cd common && make)
(cd kbx && make)
(cd sm && make && make install)
(cd tools && make gpgconf && make install)
#(cd kbx && make)
#(cd g10 && make)
# make install --list-missing -X.la -Xinfo/dir -X.pyc -Xinstall_files.txt -X__pycache__
