#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/nao/ros1_dependencies_sources/src/libgpgme-dev/debian/debian
SOURCE_DIR=/home/nao/ros1_dependencies_sources/src/libgpgme-dev/gpgme-1.10.0

cd ${DEBIAN_DIR}/patches
if [ ! -e .patched ]; then
    for patch_file in $(cat series); do
        OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false)
    done
    touch .patched
fi

cd ${SOURCE_DIR}

./configure \
  --prefix=/home/nao/${INSTALL_ROOT}/ros1_dependencies \
  --enable-static

make -j4 install
# make install --list-missing -X.la -Xinfo/dir -X.pyc -Xinstall_files.txt -X__pycache__
