axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 1.0
  y: 0.8
scale_linear_turbo:
  x: 1.5
  y: 1.2
axis_angular:
  yaw: 2
scale_angular:
  yaw: 1.0
scale_angular_turbo:
  yaw: 2.0
enable_button: 4
enable_turbo_button: 10
