topics:
- name    : bt_joy
  topic   : bluetooth_teleop/cmd_vel
  timeout : 0.5
  priority: 9
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : head_joy
  topic   : joy_head/cmd_vel
  timeout : 0.5
  priority: 7
- name    : develop_input
  topic   : develop_input/cmd_vel
  timeout : 0.5
  priority: 6
locks: []
