#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/user/ros1_dependencies_sources/src/liblcm/debian/debian
SOURCE_DIR=/home/user/ros1_dependencies_sources/src/liblcm/lcm-1.3.1

#
# constantly does not have patches
#
cd ${DEBIAN_DIR}/patches
for patch_file in $(grep -v ^# series); do
    OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false) || echo "OK"
done

cd ${SOURCE_DIR}

aclocal
libtoolize
automake --add-missing
autoconf
./configure --prefix=/opt/jsk/${INSTALL_ROOT}/ros1_dependencies

make -j${JSK_UNITREE_COMPILE_PARALLEL:-4} install
