#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/user/ros1_dependencies_sources/src/jack-audio-connection-kit/debian/debian
SOURCE_DIR=/home/user/ros1_dependencies_sources/src/jack-audio-connection-kit/jackd1-0.125.0

#
# constantly does not have patches
#
cd ${DEBIAN_DIR}/patches
for patch_file in $(grep -v ^# series); do
    OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false) || echo "OK"
done

cd ${SOURCE_DIR}

./autogen.sh
CFLAGS="-I/opt/jsk/${INSTALL_ROOT}/ros1_dependencies/include" LIBS="-L/opt/jsk/${INSTALL_ROOT}/ros1_dependencies/lib" ./configure --enable-force-install --prefix=/opt/jsk/${INSTALL_ROOT}/ros1_dependencies

make install
