#!/bin/bash

set -xeuf -o pipefail

DEBIAN_DIR=/home/user/ros1_dependencies_sources/src/flac/debian/debian
SOURCE_DIR=/home/user/ros1_dependencies_sources/src/flac/flac-1.3.2

cd ${DEBIAN_DIR}/patches
for patch_file in $(cat series); do
    OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false)
done

cd ${SOURCE_DIR}

aclocal
libtoolize
automake --add-missing
autoconf
./configure --prefix=/opt/jsk/${INSTALL_ROOT}/ros1_dependencies

make install
