#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/user/ros1_dependencies_sources/src/virtualenv/debian/debian
SOURCE_DIR=/home/user/ros1_dependencies_sources/src/virtualenv/virtualenv-15.1.0

cd ${DEBIAN_DIR}/patches
for patch_file in $(grep -v ^# series); do
    OUT="$(patch -p1 --forward --directory ${SOURCE_DIR} < ${patch_file} | tee /dev/tty)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false) || echo "OK"
done

cd ${SOURCE_DIR}

mkdir -p /opt/jsk/${INSTALL_ROOT}/ros1_dependencies/lib/python3.6/site-packages/
SKIP_PYTHON_SCRIPTS=1 \
PYTHONPATH="/opt/jsk/${INSTALL_ROOT}/ros1_dependencies/lib/python3.6/site-packages" \
          python3 \
          setup.py install \
	  --force --root=/opt/jsk/${INSTALL_ROOT}/ros1_dependencies \
	  --no-compile -O0 --single-version-externally-managed --prefix=./
#          --prefix /opt/jsk/${INSTALL_ROOT}/ros1_dependencies
