panda_effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05
  gains:
    panda_joint1: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint2: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint3: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint4: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint5: {p: 250, d: 10, i: 0, i_clamp: 1}
    panda_joint6: {p: 150, d: 10, i: 0, i_clamp: 1}
    panda_joint7: {p: 50, d: 5, i: 0, i_clamp: 1}

panda_pose_cartesian_controller:
  type: franka_example_controllers/CartesianPoseExampleController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05
  gains:
    panda_joint1: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint2: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint3: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint4: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint5: {p: 250, d: 10, i: 0, i_clamp: 1}
    panda_joint6: {p: 150, d: 10, i: 0, i_clamp: 1}
    panda_joint7: {p: 50, d: 5, i: 0, i_clamp: 1}

state_controller:
  type: franka_control/FrankaStateController
  arm_id: panda_arm
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  publish_rate: 30  # [Hz]
