#!/bin/bash 

VOICE=$1 ;
OUTPUT_FILE=tmp.wav ;
SELIF=$VOICE ;
FEELING=normal ;

if [ "$#" -gt "1" ]
then
    FEELING=$2 ;
fi ;

VOICE=`rospack find jsk_baxter_startup`/jsk_baxter_sensors/voice/Voice/mei_$FEELING;
DICTIONARY=`rospack find jtalk`/open_jtalk_dic_utf_8-1.00;

#`rospack find jtalk`/bin/
echo $SELIF | open_jtalk -td $VOICE/tree-dur.inf -tf $VOICE/tree-lf0.inf -tm $VOICE/tree-mgc.inf -md $VOICE/dur.pdf -mf $VOICE/lf0.pdf -mm $VOICE/mgc.pdf -df $VOICE/lf0.win1 -df $VOICE/lf0.win2 -df $VOICE/lf0.win3 -dm $VOICE/mgc.win1 -dm $VOICE/mgc.win2 -dm $VOICE/mgc.win3 -ef $VOICE/tree-gv-lf0.inf -em $VOICE/tree-gv-mgc.inf -cf $VOICE/gv-lf0.pdf -cm $VOICE/gv-mgc.pdf -k  $VOICE/gv-switch.inf -x $DICTIONARY -ow $OUTPUT_FILE -ot /tmp/_jtalk_log_$$.txt -s 48000 -p 240 -a 0.58 -u 0.5 -jm 0.7 -jf 0.5 -l -z 48000

if [ "$#" -gt "2" ]
then
    mv $OUTPUT_FILE $3 ;
fi ;
