# Base profile
TrajectoryPlannerROS:
  acc_lim_x: 0.55
  acc_lim_y: 0.55
  acc_lim_theta: 3.0
  max_vel_x: 0.55
  min_vel_x: 0.1
  max_vel_y: 0.55
  min_vel_y: 0.1
  max_vel_theta: 2.00
  min_vel_theta: -2.00
  min_in_place_vel_theta: 0.2
  holonomic_robot: false  