thumb_joint_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: thumb_joint
  joint_speed: 2.0
  joint_torque_limit: 0.6
  # dynamixel -> eus
  # init: 2048 -> 0
  # min:  2048 -> 0
  # max:  1024 -> 0.5 * pi
  motor:
    id: 1
    init: 2048
    min: 2048
    max: 1024
finger1_joint_controller:
  joint_name: finger1_joint_motor
  joint_speed: 1.5
  joint_torque_limit: 0.6
  calib_speed: 1.0
  calib_torque_limit: 0.2
  detect_limit_load: 0.17
  is_multiturn: true
  ignored_errors: ['DXL_OVERLOAD_ERROR']
  # dynamixel -> eus
  # init: 4096 -> 0
  # min:  8192 -> -2 * pi
  # max:  0    -> 2 * pi
  motor:
    id: 2
    init: 4096
    min: 8192
    max: 0
finger2_joint_controller:
  joint_name: finger2_joint_motor
  joint_speed: 5.5
  joint_torque_limit: 0.6
  calib_speed: 1.0
  calib_torque_limit: 0.2
  detect_limit_load: 0.17
  is_multiturn: true
  ignored_errors: ['DXL_OVERLOAD_ERROR']
  # dynamixel -> eus
  # init: 4096 -> 0
  # min:  0    -> -2 * pi
  # max:  8192 -> 2 * pi
  motor:
    id: 3
    init: 4096
    min: 0
    max: 8192
finger3_joint_controller:
  joint_name: finger3_joint_motor
  joint_speed: 5.5
  joint_torque_limit: 0.6
  calib_speed: 1.0
  calib_torque_limit: 0.2
  detect_limit_load: 0.17
  is_multiturn: true
  ignored_errors: ['DXL_OVERLOAD_ERROR']
  # dynamixel -> eus
  # init: 4096 -> 0
  # min:  8192 -> -2 * pi
  # max:  0    -> 2 * pi
  motor:
    id: 4
    init: 4096
    min: 8192
    max: 0
dxmio_heater_controller:
  controller:
    package: softhand_ros
    module: dxmio_heater_controller
    type: DxmioHeaterController
  joint_name: dxmio_heater
  motor:
    id: 5
