# Do not remap buttons in indigo
mappings:
  axes:
    - axes[0]
    - axes[1]
    - axes[2]
    - axes[3]
    - axes[4]
    - axes[5]
    - axes[6]
    - axes[7]
    - axes[8]
    - axes[9]
    - axes[10]
    - axes[11]
    - axes[12]
    - axes[13]
    - axes[14]
    - axes[15]
    - axes[16]
    - axes[17]
    - axes[18]
    - axes[19]
    - axes[20]
    - axes[21]
    - axes[22]
    - axes[23]
    - axes[24]
    - axes[25]
    - axes[26]
  buttons:
    - buttons[0]
    - buttons[1]
    - buttons[2]
    - buttons[3]
    - buttons[4]
    - buttons[5]
    - buttons[6]
    - buttons[7]
    - buttons[8]
    - buttons[9]
    - buttons[10]
    - buttons[11]
    - buttons[12]
    - buttons[13]
    - buttons[14]
    - buttons[15]
    - buttons[16]
