blacklist:
  - name: "/CPU/CPU Usage/my_machine CPU Usage"
  - name: "/Other/amcl: Standard deviation"
  - name: "/Other/jsk_joy_node: Joystick Driver Status"
  - name: "/Other/l515_head .*realsense2_camera_.*: Frequency Status"
  - name: "/Other/rosserial_python"
  - name: "/Peripherals/PS3 Controller"
  - name: "/Sensors/IMU/IMU.*"
  - name: "/SoundPlay/sound_play.*"
run_stop_blacklist:
  - name: "/Motor Control Boards/.*_(mcb|breaker)"
  - name: "/System/Mainboard/Mainboard"
    message: "Runstop pressed"
  - name: "/Breakers/.*"
    message: "Disabled."
