#!/usr/bin/env python

import argparse

from google.cloud import texttospeech


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('-eval')
    parser.add_argument('-o', '--output')
    parser.add_argument('text')
    args = parser.parse_args()

    # Instantiates a client
    client = texttospeech.TextToSpeechClient()
    with open(args.text, 'rb') as f:
        synthesis_input = texttospeech.types.SynthesisInput(
            text=f.readline())

    voice = texttospeech.types.VoiceSelectionParams(
        language_code='ja-JP',
        name='ja-JP-Wavenet-A',
        ssml_gender=texttospeech.enums.SsmlVoiceGender.FEMALE)

    # Select the type of audio file you want returned
    audio_config = texttospeech.types.AudioConfig(
        audio_encoding=texttospeech.enums.AudioEncoding.MP3)
    response = client.synthesize_speech(
        synthesis_input, voice, audio_config)
    with open(args.output, 'wb') as out:
        # Write the response to the output file.
        out.write(response.audio_content)
