name: "Conflicts Labeler"

on:
  - pull_request_target

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "PleaseResolveConflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          retryAfter: 60
          retryMax: 150
