name: "Pull Request Labeler for develop/fetch"
on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - develop/fetch_workflow_test_20230617

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        configuration-path: ".github/labeler_conf/develop_fetch_labeler.yml"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
